
os: linux
dist: bionic
language: generic

jobs:
  include:

    cache:
      directories:
        - $HOME/.dotnet

    env:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - $PATH=$PATH:$HOME/.dotnet/tools

    before_install:
      - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get -q update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get -q update
      - sudo apt-get -q install -y dotnet-sdk-3.1

    install:
      - dotnet tool update --global JetBrains.ReSharper.GlobalTools --version 2020.2.2
      - dotnet tool update --global dotnet-format --version=4.1.131201

    before_script:
      - jb cleanupcode dotnet-tools-test.sln
      - dotnet format --check dotnet-tools-test.sln

    script:
      - dotnet build
      - dotnet test
