
os: linux
dist: bionic
language: generic

jobs:
  include:

    cache:
      directories:
        - $HOME/.dotnet

    before_install:
      - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get -q update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get -q update
      - sudo apt-get -q install -y dotnet-sdk-3.1

    install:
      - dotnet tool update --global JetBrains.ReSharper.GlobalTools --version 2020.2.2

    before_script:
      - jb cleanupcode

    script:
      - dotnet build
      - dotnet test
